@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

TAbs *-right-> "1" UniqueTutorialList
TAbs *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueTutorialList
UniqueTagList -[hidden]down- UniqueTutorialList

UniqueTagList -right-> "*" Tag
UniqueTutorialList -right-> Tutorial

Tutorial -up-> "*" Tag

Tutorial *--> Name
Tutorial *--> ModuleCode
Tutorial *--> Email
Tutorial *--> Address
@enduml
