@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "TAbs Storage" #F4F6F6{
Class "<<interface>>\nTAbsStorage" as TAbsStorage
Class JsonTAbsStorage
Class JsonSerializableTAbs
Class JsonAdaptedTutorial
Class JsonAdaptedStudent
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" TAbsStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> TAbsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonTAbsStorage .up.|> TAbsStorage
JsonTAbsStorage ..> JsonSerializableTAbs
JsonSerializableTAbs --> "*" JsonAdaptedTutorial
JsonAdaptedTutorial --> "*" JsonAdaptedStudent

@enduml
