@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTAbs" as VersionedTAbs MODEL_COLOR
end box

[-> Model : undoTAbs()
activate Model

Model -> VersionedTAbs : undo()
activate VersionedTAbs

VersionedTAbs -> VersionedTAbs :resetData(ReadOnlyTAbs)
VersionedTAbs --> Model :
deactivate VersionedTAbs

[<-- Model
deactivate Model

@enduml
